steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-west1-docker.pkg.dev/drive-wizard-2/docker-repo/drive-api-hello:$COMMIT_SHA',
      '.'
    ]

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west1-docker.pkg.dev/drive-wizard-2/docker-repo/drive-api-hello:$COMMIT_SHA'
    ]

  # 3. Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'drive-api-hello'
      - '--image=us-west1-docker.pkg.dev/drive-wizard-2/docker-repo/drive-api-hello:$COMMIT_SHA'
      - '--region=us-west1'
      - '--allow-unauthenticated'
      # Optional:
      # - '--service-account=drive-api-access@drive-wizard-2.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
